import { Project } from './types';

export const PROJECTS: Project[] = [
  { id: "mx-mangroves", name: "Yucatán Mangroves", country: "Mexico", pricePerM2: 1, impact: { biodiversity: 92, carbon: 88, community: 74 }, lat: 20.5, lon: -90.5, image: "/reserve/project-images/mx-mangroves.jpg" },
  { id: "br-amazon", name: "Tapajós Rainforest", country: "Brazil", pricePerM2: 0.8, impact: { biodiversity: 98, carbon: 95, community: 80 }, lat: -3.2, lon: -55.1, image: "/reserve/project-images/br-amazon.jpg" },
  { id: "id-seagrass", name: "Bali Seagrass", country: "Indonesia", pricePerM2: 1.2, impact: { biodiversity: 85, carbon: 72, community: 77 }, lat: -8.5, lon: 115.2, image: "/reserve/project-images/id-seagrass.jpg" },
  { id: "ke-savanna", name: "Laikipia Savanna", country: "Kenya", pricePerM2: 0.6, impact: { biodiversity: 76, carbon: 61, community: 82 }, lat: 0.3, lon: 37.0, image: "/reserve/project-images/ke-savanna.jpg" },
  { id: "us-cal-giants", name: "Redwood Groves", country: "USA", pricePerM2: 1.1, impact: { biodiversity: 80, carbon: 90, community: 70 }, lat: 40.3, lon: -124.0, image: "/reserve/project-images/us-cal-giants.jpg" },
  { id: "ca-boreal", name: "Boreal Shield", country: "Canada", pricePerM2: 0.7, impact: { biodiversity: 73, carbon: 88, community: 65 }, lat: 54.7, lon: -94.2, image: "/reserve/project-images/ca-boreal.jpg" },
  { id: "ar-wetlands", name: "Iberá Wetlands", country: "Argentina", pricePerM2: 0.9, impact: { biodiversity: 86, carbon: 70, community: 72 }, lat: -28.6, lon: -57.4, image: "/reserve/project-images/ar-wetlands.jpg" },
  { id: "pe-cloud", name: "Andean Cloud", country: "Peru", pricePerM2: 1.0, impact: { biodiversity: 90, carbon: 84, community: 78 }, lat: -9.0, lon: -75.0, image: "/reserve/project-images/pe-cloud.jpg" },
  { id: "ng-mangrove", name: "Niger Delta Mangroves", country: "Nigeria", pricePerM2: 0.6, impact: { biodiversity: 75, carbon: 82, community: 79 }, lat: 4.9, lon: 6.1, image: "/reserve/project-images/ng-mangrove.jpg" },
  { id: "ma-atlas", name: "High Atlas", country: "Morocco", pricePerM2: 0.8, impact: { biodiversity: 70, carbon: 55, community: 76 }, lat: 31.1, lon: -7.9, image: "/reserve/project-images/ma-atlas.jpg" },
  { id: "es-donana", name: "Doñana Marshes", country: "Spain", pricePerM2: 0.9, impact: { biodiversity: 78, carbon: 61, community: 74 }, lat: 37.0, lon: -6.5, image: "/reserve/project-images/es-donana.jpg" },
  { id: "ro-delta", name: "Danube Delta", country: "Romania", pricePerM2: 0.85, impact: { biodiversity: 84, carbon: 66, community: 71 }, lat: 45.1, lon: 29.6, image: "/reserve/project-images/ro-delta.jpg" },
  { id: "ua-steppe", name: "Pontic Steppe", country: "Ukraine", pricePerM2: 0.5, impact: { biodiversity: 60, carbon: 50, community: 68 }, lat: 48.2, lon: 34.8, image: "/reserve/project-images/ua-steppe.jpg" },
  { id: "ru-taiga", name: "Siberian Taiga", country: "Russia", pricePerM2: 0.4, impact: { biodiversity: 65, carbon: 92, community: 60 }, lat: 62.0, lon: 90.0, image: "/reserve/project-images/ru-taiga.jpg" },
  { id: "in-sundarbans", name: "Sundarbans", country: "India", pricePerM2: 0.7, impact: { biodiversity: 88, carbon: 76, community: 70 }, lat: 21.9, lon: 89.2, image: "/reserve/project-images/in-sundarbans.jpg" },
  { id: "np-terai", name: "Terai Arc", country: "Nepal", pricePerM2: 0.9, impact: { biodiversity: 87, carbon: 69, community: 78 }, lat: 27.6, lon: 84.4, image: "/reserve/project-images/np-terai.jpg" },
  { id: "th-coral", name: "Andaman Coral", country: "Thailand", pricePerM2: 1.2, impact: { biodiversity: 92, carbon: 60, community: 80 }, lat: 8.0, lon: 98.3, image: "/reserve/project-images/th-coral.jpg" },
  { id: "au-reef", name: "Great Barrier", country: "Australia", pricePerM2: 1.4, impact: { biodiversity: 95, carbon: 50, community: 75 }, lat: -18.2, lon: 147.7, image: "/reserve/project-images/au-reef.jpg" },
  { id: "pg-png", name: "PNG Rainforest", country: "Papua New Guinea", pricePerM2: 0.9, impact: { biodiversity: 94, carbon: 88, community: 72 }, lat: -6.3, lon: 145.6, image: "/reserve/project-images/pg-png.jpg" },
  { id: "za-fynbos", name: "Cape Fynbos", country: "South Africa", pricePerM2: 0.8, impact: { biodiversity: 93, carbon: 54, community: 76 }, lat: -33.9, lon: 19.1, image: "/reserve/project-images/za-fynbos.jpg" },
  { id: "mg-madagascar", name: "Madagascar Forests", country: "Madagascar", pricePerM2: 0.7, impact: { biodiversity: 97, carbon: 66, community: 68 }, lat: -18.8, lon: 47.6, image: "/reserve/project-images/mg-madagascar.jpg" },
  { id: "ma-seagrass", name: "Mediterranean Seagrass", country: "Morocco", pricePerM2: 1.0, impact: { biodiversity: 80, carbon: 70, community: 73 }, lat: 35.7, lon: -5.6, image: "/reserve/project-images/ma-seagrass.jpg" },
  { id: "no-bogs", name: "Nordic Peat Bogs", country: "Norway", pricePerM2: 0.6, impact: { biodiversity: 68, carbon: 83, community: 66 }, lat: 61.2, lon: 8.0, image: "/reserve/project-images/no-bogs.jpg" },
  { id: "uk-heath", name: "Dorset Heaths", country: "UK", pricePerM2: 0.7, impact: { biodiversity: 72, carbon: 55, community: 70 }, lat: 50.8, lon: -2.2, image: "/reserve/project-images/uk-heath.jpg" },
  { id: "tr-anatolia", name: "Anatolian Steppe", country: "Türkiye", pricePerM2: 0.5, impact: { biodiversity: 66, carbon: 48, community: 69 }, lat: 39.0, lon: 35.2, image: "/reserve/project-images/tr-anatolia.jpg" },
  { id: "ir-wetland", name: "Mesopotamian Marshes", country: "Iraq", pricePerM2: 0.7, impact: { biodiversity: 78, carbon: 58, community: 74 }, lat: 30.9, lon: 47.2, image: "/reserve/project-images/ir-wetland.jpg" },
  { id: "cn-giantpanda", name: "Sichuan Panda", country: "China", pricePerM2: 1.1, impact: { biodiversity: 88, carbon: 63, community: 75 }, lat: 31.5, lon: 103.8, image: "/reserve/project-images/cn-giantpanda.jpg" },
  { id: "jp-sea", name: "Seto Inland Sea", country: "Japan", pricePerM2: 1.0, impact: { biodiversity: 82, carbon: 62, community: 79 }, lat: 34.4, lon: 133.8, image: "/reserve/project-images/jp-sea.jpg" },
  { id: "nz-kelp", name: "Kelp Forests", country: "New Zealand", pricePerM2: 1.2, impact: { biodiversity: 90, carbon: 65, community: 77 }, lat: -45.1, lon: 168.6, image: "/reserve/project-images/nz-kelp.jpg" },
  { id: "is-highlands", name: "Iceland Highlands", country: "Iceland", pricePerM2: 0.9, impact: { biodiversity: 60, carbon: 72, community: 68 }, lat: 64.9, lon: -18.6, image: "/reserve/project-images/is-highlands.jpg" },
  { id: "maurit-corals", name: "Mascarene Corals", country: "Mauritius", pricePerM2: 1.1, impact: { biodiversity: 92, carbon: 55, community: 80 }, lat: -20.2, lon: 57.5, image: "/reserve/project-images/maurit-corals.jpg" },
  { id: "eg-nile", name: "Nile Delta", country: "Egypt", pricePerM2: 0.8, impact: { biodiversity: 70, carbon: 58, community: 76 }, lat: 30.9, lon: 31.3, image: "/reserve/project-images/eg-nile.jpg" },
  { id: "sa-mangrove", name: "Arabian Mangroves", country: "Saudi Arabia", pricePerM2: 0.9, impact: { biodiversity: 75, carbon: 62, community: 69 }, lat: 21.5, lon: 39.2, image: "/reserve/project-images/sa-mangrove.jpg" }
];
